### ISSUE TITLE
Same issues like #50, it doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by binhvcom** [ncabatoff/process-exporter#120]
i am using v0.5.0 (on Ubuntu 18.04).
i have run it with grafana, prometheus, used config like this 
`/etc/process-exporter/all.yaml`

```
process_names:
  - name: "{{.Comm}}"
    cmdline: 
    - '.+'
```

`/lib/systemd/system/process-exporter.service`

```
[Unit]
Description=Process Exporter for Prometheus

[Service]
User=root
Type=simple
ExecStart=/usr/bin/process-exporter --config.path /etc/process-exporter/all.yaml --web.listen-address=:9256
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

But when i run, i have this problem (it won't record anything on grafana)

```
systemctl status process-exporter
● process-exporter.service - Process Exporter for Prometheus
   Loaded: loaded (/lib/systemd/system/process-exporter.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-09-24 16:54:30 +07; 1h 3min ago
 Main PID: 7420 (process-exporte)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/process-exporter.service
           └─7420 /usr/bin/process-exporter --config.path /etc/process-exporter/all.yaml --web.listen-address=:9256

Sep 24 16:54:30 loki-host systemd[1]: Started Process Exporter for Prometheus.
Sep 24 16:54:30 loki-host process-exporter[7420]: 2019/09/24 16:54:30 Reading metrics from /proc based on "/etc/process-exporter/all.yaml"
```

**Comment by binhvcom** [comment]
this is my prometheus config
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'process-exporter'
    #scrape_interval: 5s
    static_configs:
    - targets: ['locahost:9256']

  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
```
