### ISSUE TITLE
Getting metrics on all process/threads

### ISSUE THREAD

**Issue by arunnalpet** [ncabatoff/process-exporter#121]
How can we match all the processes, like as seen by 'ps aux' or 'top' command? 

process-exporter is matching less number of process, inspite of giving the following reg-ex:

```
process_names:
  - cmdline:
    - .+
  - exe:
    - .+
  - comm:
    - .+

```
