### ISSUE TITLE
namedprocess_namegroup_open_filedesc doesn't display correct result

### ISSUE THREAD

**Issue by whlcmhh** [ncabatoff/process-exporter#123]
Centos 7.4
process-exporter-0.4.0.linux-amd64

config.yml:
```
   process_names:
   - name: "apirouter"
     comm:
     - java 
     cmdline:
     - hyperspace

```
I can get most correct result except namedprocess_namegroup_open_filedesc , which's result is 0.
According to documents, the open_filedesc comes form /proc/pid/fd , and i check the target process's fd directoy in which i find many entries.

So i want to know if my usuage is wrong. If it is , how can i get correct result?
