### ISSUE TITLE
Need help with Config file format

### ISSUE THREAD

**Issue by lozbrown** [ncabatoff/process-exporter#136]
I've been trying to get this working for 2 hours now,  I'm baffled by the config file format

I have a load of process that look like this in ps -ef 
`/app/dvkdbhk/home/dvkdbhkx/indexCalc//q/l64/q /app/dvkdbhk/home/dvkdbhkx/indexCalc/script/q/r.q -w 15000 -p 4509`

each one will have a different command line argument but a different start. 

i want each one to be an different individually named process 
```
process_names:
    - name: RDB
    exe:
    - /app/dvkdbhk/home/dvkdbhkx/indexCalc//q/l64/q
    cmdline:
    - /app/dvkdbhk/home/dvkdbhkx/indexCalc/script/q/tick/r.q

```

I've tried lots of different changes and i keep getting config file issues, can anybody give me a hint here
2020/03/03 11:17:39 error reading config file "./config.yml": yaml: line 2: did not find expected '-' indicator
