### ISSUE TITLE
How do I monitor multiple processes with the same name?

### ISSUE THREAD

**Issue by xiamuran1** [ncabatoff/process-exporter#147]
How do you monitor a process that starts multiple instances of a service and listens on different ports?

**Comment by graudeejs** [comment]
This helped me
```
process_names:
  - name: "{{.ExeFull}}"
    cmdline:
      - '.+'
```
