### ISSUE TITLE
Can not get metrics for nodejs, after upgrade from node 8 to node12

### ISSUE THREAD

**Issue by SjhZju** [ncabatoff/process-exporter#154]
Hi,
     I try to use process_exporter to get nodejs process metrics.  It worked well before. But I get nothing after I upgrade nodejs
 version from node-8.12.0 to node-12.15.0 last week。
     server OS：centos-7.2.1511
     ps result:   
    `root     22591  6.5  5.0 438188 188420 ?       Sl   Jul02  71:08 node --inspect /var/lib/nodepr/be/main.js --stage=null --stage=prod`
     config:
```
process_names:
  - name: nodejs
    comm:
    - node
    cmdline:
    - main\.js
```
Thanks
