### ISSUE TITLE
Possible bug in PSS and RSS memory measurement

### ISSUE THREAD

**Issue by itsx** [ncabatoff/process-exporter#164]
Hi, first Thank You for a fantastic new release **0.7.2** with newly added **PSS** memory metrics, which is really cool and useful !

**Problem:**
We upgraded process-exporter on all of our machines and spotted that **for some processes we have bigger PSS than RSS**. For example **minio** process:

```
namedprocess_namegroup_memory_bytes{groupname="minio",memtype="proportionalResident"} 6.0010496e+07
namedprocess_namegroup_memory_bytes{groupname="minio",memtype="proportionalSwapped"} 0
namedprocess_namegroup_memory_bytes{groupname="minio",memtype="resident"} 4.9995776e+07
namedprocess_namegroup_memory_bytes{groupname="minio",memtype="swapped"} 0
namedprocess_namegroup_memory_bytes{groupname="minio",memtype="virtual"} 2.95735296e+08
```

which is, as far as I can tell, not correct.

I checked this minio process with **smem** utility and its output looks correct:
```
PID User     Command                         Swap      USS      PSS      RSS
...
23258 minio    minio server /data --addres        0    58648    58648    58652
```

Also values in **/proc/PID/smaps** looks ok and corresponds to **smem** output:

```
sudo cat /proc/23258/smaps | grep '^Pss\|^Rss'
Rss:                5952 kB
Pss:                5952 kB
Rss:                5600 kB
Pss:                5600 kB
Rss:                 240 kB
Pss:                 240 kB
Rss:                  92 kB
Pss:                  92 kB
Rss:               32344 kB
Pss:               32344 kB
Rss:                2048 kB
Pss:                2048 kB
Rss:                1728 kB
Pss:                1728 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   8 kB
Pss:                   8 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:               10616 kB
Pss:               10616 kB
Rss:                  20 kB
Pss:                  20 kB
Rss:                   0 kB
Pss:                   0 kB
Rss:                   4 kB
Pss:                   0 kB
Rss:                   0 kB
Pss:                   0 kB
```

We are using Ubuntu 18.04 and there is just one minio process on the machine.
Please can you hint me to some explanation. I can imagine this is a bug, or maybe 
I am missing something. 

For completeness, we run process-exporter natively as a service (without docker):
`/usr/bin/process-exporter --config.path /etc/process-exporter/process-exporter.yml --web.listen-address=:9256 -threads=false`

And this is our config:
```
process_names:
  # Java grouping
  - name: "elasticsearch"
    comm:
    - java
    cmdline:
    - '.*elasticsearch.*'

  - name: "{{.Comm}}:{{.Matches.JavaCommandline}}"
    comm:
    - java
    cmdline:
    - '(?P<JavaCommandline>.*)'

  # Python grouping      
  - name: "{{.Comm}} {{.Matches.PythonSwitch}}:{{.Matches.PythonProgram}}"
    comm:
    - python
    - python2
    - python3
    cmdline:
    - 'python\d?\s?(?P<PythonSwitch>-?\S{0,3})\s+(?P<PythonProgram>\S+)'

  # Thanos grouping  
  - name: "{{.Comm}}:{{.Matches.ThanosCommand}}"
    comm:
    - thanos
    cmdline:
    - 'thanos\s+(?P<ThanosCommand>\S+)'

  # Celery grouping
  - name: "{{.Comm}}:{{.Matches.CeleryApp}}:{{.Matches.CeleryQueue}}"
    comm:
    - celery
    cmdline:
    - '--app=app\s+(?P<CeleryApp>\S+).+--queues=celery\.(?P<CeleryQueue>\S+)'

  - name: "{{.Comm}}:{{.Matches.CeleryApp}}"
    comm:
    - celery
    cmdline:
    - '--app=app\s+(?P<CeleryApp>\S+)'

  # Default grouping
  - name: "{{.Comm}}"
    cmdline:
    - '.+'
```
