### ISSUE TITLE
support for CentOS 6

### ISSUE THREAD

**Issue by ndelic0** [ncabatoff/process-exporter#165]
Does process_exporter support  monitoring processes running  on el6/centos6? 
If I run it with default config:
```
---
process_names:
  - name: "{{.Comm}}"
    cmdline: 
    - '.+'`
```
it would only allow monitoring limited set of stats.
