### ISSUE TITLE
Scrap metrics timeout when a process has too many pid

### ISSUE THREAD

**Issue by pretendhigh** [ncabatoff/process-exporter#188]
env:
ubuntu 16.04
process_exporter 0.7.5 or 0.6.0
airflow 1.10.12
process.conf :
```
process_names:
  - name: "{{.Matches}}"
    cmdline:
      - 'celeryd'
```
When airflow celery worker_concurrency up to 1500, it will be a long time about 1min  to get localost:9256/metrics. When celery worker_concurrency up to 2000, it will cost 5 to 15 min to get the metrics causing prometheus scrape timeout. The available cpu and memory is enougth.
