### ISSUE TITLE
Disk IO (read / write bytes) reported as nought always for all configured processes

### ISSUE THREAD

**Issue by MurzNN** [ncabatoff/process-exporter#190]
I use process-exporter package on Ubuntu 20.04 system (direct package from Ubuntu repository, version 0.4.0+ds-1, without docker), and have the problem, that it reports nought results in disk IO (read / write bytes) for all processes. But when using other tools such as `atop` - I see always increasing numbers for same processes.

For example, `mysqld` process - reports always zero in `process-exporter` metrics list:
```
namedprocess_namegroup_read_bytes_total{groupname="mysqld"} 0
namedprocess_namegroup_write_bytes_total{groupname="mysqld"} 0
```

If I try to manually fetch raw stat from `mysqld` proc (by it's pid), I see non-zero and increasing numbers too:
```
# cat /proc/3851/io 
rchar: 223227953195
wchar: 152972530386
syscr: 13503811
syscw: 18800057
read_bytes: 16305747066880
write_bytes: 242041810944
cancelled_write_bytes: 1045590016
```

Other reported by process-exporter metrics, like `cpu` are not zero and increases successfully:
```
namedprocess_namegroup_thread_cpu_seconds_total{cpumode="system",groupname="mysqld",threadname="mysqld"} 35395.739999999976
namedprocess_namegroup_thread_cpu_seconds_total{cpumode="user",groupname="mysqld",threadname="mysqld"} 46885.01999999971
```
after some seconds becomes:
```
namedprocess_namegroup_thread_cpu_seconds_total{cpumode="system",groupname="mysqld",threadname="mysqld"} 35408.30999999997
namedprocess_namegroup_thread_cpu_seconds_total{cpumode="user",groupname="mysqld",threadname="mysqld"} 46899.70999999971
```

Same problem is for all other processes too.

Here is my filter rules:
```yaml
process_names:
  - comm:
    - php
    - mysqld

  - name: keystone
    comm:
    - sh
    cmdline:
    -  '/bin/sh -c keystone-next start'

  - name: solr
    comm:
    - java
    cmdline:
    -  '/opt/solr/solr'
```

Can you describe where can be the problem and what can I do more to find the source of this problem? Thanks!
