### ISSUE TITLE
Processes not groupped correctly on rare occasions

### ISSUE THREAD

**Issue by jacekn** [ncabatoff/process-exporter#191]
I have a process (`/usr/bin/main-process`) that periodically spawns subprocesses. To allow me to monitor memory usage of the main process without children I used the following config:
```
process_names:
  - name: main-process
    cmdline:
    - /usr/bin/main-process .*
  - name: ignored-group
    cmdline:
    - /usr/bin/python3 .*|/usr/bin/curl .*
```

Above works, `python3` and `curl` subprocesses are encapsulated into the `ignored-group` and memory and other metrics are not included in the `main-process` group.
However I noticed that on a rare occasions processes are not grouped properly and I see "spikes" when the `ignored-group` process count is 0 and there is a memory usage spike reported in the `main-process` that matches expected memory usage of the `ignored-group`.
I confirmed that using `ps` on the system too. Every time I see the unexpected spike in the `main-process` memory usage there are subprocesses running. In most cases everything is correct and the subprocesses go into their own group but looks like there may be a race that causes the grouping to not work sometimes.
