### ISSUE TITLE
process_exporter (host without prometheus) -> another host with prometheus -> grafana

### ISSUE THREAD

**Issue by BoogerMan2103** [ncabatoff/process-exporter#196]
#### Hello! 
I`m trying to add process metrics to grafana dashboard from one instance process_exporter from host without prometheus to another instance with prometheus and grafana.
config process_exporter (source host) :
```
cat /etc/process-exporter/all.yaml 
process_names:
  - name: "{{.Comm}}"
    cmdline:
    - '.+'
```
Metrics has been ok check via `curl localhost:9256/metrics`

Also check from target host via curl:

```
curl 192.168.1.200:9526/metrics | grep nginx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
namedprocess_namegroup_context_switches_total{ctxswitchtype="nonvoluntary",groupname="nginx"} 3
namedprocess_namegroup_context_switches_total{ctxswitchtype="voluntary",groupname="nginx"} 774
namedprocess_namegroup_cpu_seconds_total{groupname="nginx",mode="system"} 0.040000000000000036
namedprocess_namegroup_cpu_seconds_total{groupname="nginx",mode="user"} 0.08000000000000007
...
```

Prometheus config about exporter on target host:
```
scrape_configs:
  - job_name: 'process_dev_worker'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: "/metrics"
    static_configs:
    - targets: ['192.168.1.200:9526']
```
Prometheus get some parameters from instance via selector `{instance="192.168.1.200:9526",job="process_dev_worker"} ` like with:
```
scrape_duration_seconds
scrape_samples_post_metric_relabeling
scrape_samples_scraped
scrape_series_added
up
```
and nothing else

**Question: How to config prometheus to get all metrics/labels from process_exporter and draw graph in grafana?**
