### ISSUE TITLE
too resources consumption

### ISSUE THREAD

**Issue by FStefanni** [ncabatoff/process-exporter#201]
Hi,

I have a server, for which I monitor the relevant processes with this:
```
process_names:
   - name: "{{.Comm}}"
     cmdline:
     - '.*VBox.*|.*docker.*|.*Docker.*|.*container.d.*|.*openvpn.*'
```

This issue is that it still uses too much resources (in that server I have about 170 docker containers).
After a while of starting process-exporter, the server collapses... (especially for the CPU usage)

So there is a way to limit or optimize process-exporter resource usage?

Thank you.
Regards
