### ISSUE TITLE
arm64 Docker image doesn't start

### ISSUE THREAD

**Issue by goldyfruit** [ncabatoff/process-exporter#209]
I'm trying to run this exporter on a Raspberry Pi 4 64-bit it seems that the image doesn't work.
```
standard_init_linux.go:228: exec user process caused: exec format error
```
Here is my `docker-compose.yml` file:
```yaml
version: '3.8'
  process_exporter:
    image: ncabatoff/process-exporter:latest
    command:
      - config.path /config/process.yml
    container_name: process_exporter
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - ./config:/config
```

And this is my `process.yml` file:
```yaml
process_names:
  - name: "{{.Comm}}"
    cmdline:
    - '.+'
```
