### ISSUE TITLE
Can't match a process with a dot in it

### ISSUE THREAD

**Issue by theocerutti** [ncabatoff/process-exporter#224]
Hello,

I want to get metrics of the processus running in my docker containers.
I have a process named "standalone.sh" (it is a script ran by the container using `exec "./standalone.sh"`), the problem is that process-exporter is mining the metrics of the process "bash" instead of "standalone.sh"...

Here is my config:
```bash
process_names:
  - comm:
    - python3
    - java
    - mysqld
    - mariadbd
    - mongod
    - haproxy
    - standalone.sh
```

**Comment by theocerutti** [comment]
It seems that with this config: 
```yml
process_names:
  - name: mycontainer
    comm:
      - standalone.sh
```

**Comment by theocerutti** [comment]
It seems that with this config: 
```yml
process_names:
  - name: mycontainer
    comm:
      - standalone.sh
```
