### ISSUE TITLE
Enable/Disable threads on specific programs

### ISSUE THREAD

**Issue by Lusitaniae** [ncabatoff/process-exporter#314]
Since threads adds a lot of overhead and cardinality to metrics, would be interesting if we could restrict threads to one of the multiple process monitored by process exporter

**Comment by Lusitaniae** [comment]
For now doing that on prometheus / scraping side by using metrics relabel

so as to only keep thread metrics for my app1/app2, nothing else

```
    metric_relabel_configs:
    # introduces too much cardinality causing issues in Prometheus / Victoria Metrics
    # only keep thread info for Agave or SUI
      - action: keep
        source_labels: [__name__, groupname]
        regex: namedprocess_namegroup_thread_.*;(app1|app2).*
```
