### ISSUE TITLE
How can the process of the root user not be matched?

### ISSUE THREAD

**Issue by SXISZERO** [ncabatoff/process-exporter#354]
My configuration file is as follows. I don't want to match the process of the root user, but the regular expression of cmdline uses "^(?". ! root).*”
An error will be displayed.

```
process_names:
  - name: "{{.Username}}:{{.PID}}:{{.ExeBase}}"
    cmdline:
      - '^(?!root).*'
```

2025/06/25 10:42:01 error reading config file "process-exporter.yml": bad cmdline regex "^(?!root).*": error parsing regexp: invalid or unsupported Perl syntax: `(?!`
