### ISSUE TITLE
Detecting Java processes by parameter, RegEx in `cmdline` not working

### ISSUE THREAD

**Issue by mar1ged** [ncabatoff/process-exporter#44]
I tried to translate a working regex into the shape that your config file needs but failed. I already tried to "debug" this but failed also.

This regex on its own works:
`-Dprocess_name=(?P<process>[\w\d_-]*)`

I ran it through regex101 and it works as intended:
![101](https://user-images.githubusercontent.com/16045549/41602273-bee01842-73da-11e8-96a2-51c6b0982f9d.png)

The same in a config does not yield a result:
```
process_names:
  - comm:
    - bash

  - exe:
    - nginx

  - name: "{{.ExeFull}}:{{.Matches.process}}"
    exe:
    - java
    cmdline:
    - -Dprocess_name=(?P<process>[\\w\\d_-]*)
```

I also checked with `ps`, there are enough Java processes that fit this pattern.

In the exported metrics I can see the process, but the process name from the `-D` is missing:

`namedprocess_namegroup_cpu_system_seconds_total{groupname="/var/opt/jdk9/bin/java:"} 0.060000000000044906
`

Where is my mistake ?

I also tried your example from the readme (removing the scan for prometheus, postgres and bash):

```
process_names:
  - name: "{{.ExeFull}}:{{.Matches.Cfgfile}}"
    exe:
    - /usr/local/bin/process-exporter
    cmdline:
    - -config.path\\s+(?P<Cfgfile>\\S+)
```

Even this (proven ?) example does not work. I run process exporter and can see that the process is running:
`root     14818  1.7  0.0  14848  6916 pts/2    Sl   07:42   0:00 ./process-exporter -config.path bsp.yml`

When I run `curl http://localhost:9256/metrics | grep "^namedprocess"` this is all I get:
```
namedprocess_scrape_errors 0
namedprocess_scrape_partial_errors 0
namedprocess_scrape_procread_errors 0
```
