### ISSUE TITLE
Alerting on missing processes upon startup

### ISSUE THREAD

**Issue by geekdave** [ncabatoff/process-exporter#59]
Hello,

First of all, thank you for creating and maintaining this project!  It's been a big help for us.  

We have an alert set up like this to fire if any expected processes are not running:

```
alert: ProcessNotRunning
expr: namedprocess_namegroup_num_procs
  < 1
for: 1m
labels:
  severity: page
annotations:
  description: '{{ $labels.groupname }} process missing on {{ $labels.instance }}'
  summary: '{{ $labels.groupname }} process on {{ $labels.instance }} has not been
    running for 1 min.'
```

One thing I just noticed is that if some expected processes are not running _at the time when I start process-exporter_ then I get no metrics about them.  This means that if an instance restarts, we need to manually check that all expected processes are running.

Wondering if I'm doing something wrong, or if there is another way to go about this.  Everything works great if the process is already running at the time when I start process_exporter.

Here is how I'm starting process-exporter (using dummy processes top and tail for demo purposes):

```
  docker run \
   -d \
   --privileged \
   --name process_exporter \
   -v /proc:/host/proc \
   -p 9256:9256 \
   ncabatoff/process-exporter:0.3.9 \
   --procfs /host/proc \
   -procnames top,tail
```

Thanks!
Dave
