### ISSUE TITLE
crash on multiple exe: match

### ISSUE THREAD

**Issue by powerman** [ncabatoff/process-exporter#6]
I'm usually have just one `mono` process, but today I've started another one and process-exporter crashed. Here are these processes:

```
# ps ax | grep mono
30225 pts/15   Sl+    0:01 mono wdmrc.exe -p 10801
32293 ?        Sl     1:40 mono --verify-all /usr/lib64/keepass/KeePass.exe
```

My config:

```
process_names:
  - comm:
    - bash
    - dropbox
    - firefox
    - goldendict
    - grafana-server
    - mc
    - mutt
    - mysqld
    - node-exporter
    - pidgin
    - process-exporter
    - prometheus
    - rtorrent main
    - urxvt
    - vi
    - VirtualBox

  - name: KeePass
    exe:
    - mono
    cmdline:
    - KeePass
```

Panic:

```
2017/02/06 01:37:14 Reading metrics from /proc based on "config.yml"
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x7b1ba0, 0xc420014090)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/ncabatoff/process-exporter/config.(*cmdlineMatcher).Match(0xc42012e9c0, 0xc420380ca8, 0x4, 0xc420360c80, 0x4, 0x4, 0xc4202fc001)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/config/config.go:118 +0x1ed
github.com/ncabatoff/process-exporter/config.andMatcher.Match(0xc42012e9e0, 0x2, 0x2, 0xc420380ca8, 0x4, 0xc420360c80, 0x4, 0x4, 0xc4202fc000)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/config/config.go:126 +0x74
github.com/ncabatoff/process-exporter/config.(*matchNamer).MatchAndName(0xc42012ea00, 0xc420380ca8, 0x4, 0xc420360c80, 0x4, 0x4, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/config/config.go:68 +0x85
github.com/ncabatoff/process-exporter/config.FirstMatcher.MatchAndName(0xc42012ea20, 0x2, 0x2, 0xc420380ca8, 0x4, 0xc420360c80, 0x4, 0x4, 0x9ffa40, 0x0, ...)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/config/config.go:60 +0x7f
github.com/ncabatoff/process-exporter/config.(*FirstMatcher).MatchAndName(0xc42012ea60, 0xc420380ca8, 0x4, 0xc420360c80, 0x4, 0x4, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x8b
github.com/ncabatoff/process-exporter/proc.(*Grouper).Update(0xc420128f90, 0x9e6660, 0xc4200572c0, 0x0, 0xc420129020, 0x50)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/proc/grouper.go:85 +0x295
main.NewProcessCollector(0x81b465, 0x5, 0xc42012ea01, 0x9e0680, 0xc42012ea60, 0x18, 0xc420130080, 0xc420125ad0)
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/cmd/process-exporter/main.go:274 +0x2e3
main.main()
	/home/powerman/gocode/src/github.com/ncabatoff/process-exporter/cmd/process-exporter/main.go:218 +0x6b5
```
