### ISSUE TITLE
namedprocess_namegroup_read_bytes_total seems to be always zero

### ISSUE THREAD

**Issue by mardicas** [ncabatoff/process-exporter#66]
Hi,
it seems namedprocess_namegroup_read_bytes_total is always 0. 
namedprocess_namegroup_write_bytes_total seems to be OK.

Using latest version 0.4.0

```
# uname -a
Linux driver 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Configuration:
```
process_names:
  - exe: 
    - /opt/java/jdk1.8.0_92/bin/java
    cmdline: 
    - com.connecty.collector.DataCollector
    name: collector
  - exe:
    - /opt/java/jdk1.8.0_92/bin/java
    cmdline:
    - -Dcatalina.base=/var/lib/tomcat/fm
    name: fm
  - exe:
    - /opt/java/jdk1.8.0_92/bin/java
    cmdline:
    - -Dcatalina.base=/var/lib/tomcat/mk3
    name: mk3
  - exe:
    - node
    name: node
  - exe:
    - /usr/bin/redis-server
    name: redis
```
