### ISSUE TITLE
Need more documentation/examples how to match process names

### ISSUE THREAD

**Issue by vkuznet** [ncabatoff/process-exporter#85]
Hi, I'm having hard time to understand config syntax and more example will be helpful. For instance, I have plenty of python process on a system but they use different arguments, e.g.
```
python -u /path --init=arg1
python -u /path --init=arg2
```
My question is how I can match only process with certain argument? I came up with this config:
```
process_names:
 - comm:
   - python
   cmdline:
   - *.arg1.*
```
but it fails with error `did not find expected alphabetic or numeric character`. But if I do this:
```
process_names:
 - comm:
   - python
 - exe:
   - python
   cmdline:
   - .*arg1.*
```
it works. So it is unclear where cmdline should be applied.

Generally speaking better documentation or more examples would be extremely useful.

On a similar subject when process-exporter starts it would be nice if it will printout which processes and/or PIDs it matched. For instance, if I use this config
```
process_names:
 - comm:
   - python
- exe
  - python
  cmdline:
  - .*.arg1.*
```
I would expect that it should match only process which has arg1 argument. But from debug output I see that it matches all python processes.

And, on a client side it would be nice if the output will contain the actual PID of matched processes. Then it would be clear that what was matched and metrics is provided for particular PID.

**Comment by richard001100** [comment]
Hey this is possible as im doing something similar with this currently 

my config looks something like the below : 

- name: "name i give to this lookup"
  exe:
            - /path/to/exe/location/
  cmdline:
            - command line lookup here

if you had a program that was for say myexe and command line was something like -f thisconfig2.yml your cmdline would look something like 

- name: "generation lookup config2"
  exe: 
        - /path/to/exe/location/myexe
  cmdline:
        - \s+thisconfig.yml
 
\s being a space between the exe and the next param on the command line 

if you run process-exporter in a debug mode you should see if it matches also.

**Comment by richard001100** [comment]
\- not a bullet point of course

**Comment by vkuznet** [comment]
Eventually I figure out config which can suit my use-case, i.e. match one python process with specific argument. Here it is
```
process_names:
 - exe:
   - python
   cmdline:
   - ".*arg.*"
```
where `arg` is a pattern I wanted to be matched with python process string, i.e. from this python process string:
```
python -u /path --ini=/path/arg.py
```
