### ISSUE TITLE
Group by process owner name

### ISSUE THREAD

**Issue by vkuznet** [ncabatoff/process-exporter#86]
It would be nice to match processes by specifying process owner name/account, e.g. match processes owned by apache user name. Would it be possible?

**Comment by baryluk** [comment]
+100

I would like to have this for postgresql and apache that is also running some cgi scripts.

Example of what I would like to be able to do:

```
process_names:
   - name: postgresql
     username: postgresql

  - name: webserver
     uid: 33
```
