### ISSUE TITLE
unable to view named process in grafana

### ISSUE THREAD

**Issue by lakshmanvvs** [ncabatoff/process-exporter#9]
I'm using the docker image for this, but unable to view any data points for named_process. 
What could be missing?

**Comment by ncabatoff** [comment]
I can speculate, but I'm more likely to give you something useful if you provide the command line you use to launch the container and the output of your GET /metrics call.

**Comment by lakshmanvvs** [comment]
This is a part of my docker compose file for the process exporter 
```
processexporter:
    image: lakshmanvvs/process-exporter
    container_name: processexporter
    volumes:
      - /proc:/host/proc
    command:
      - '-procfs=/host/proc'
      - '-procnames=chromium-browse,bash,prometheus,gvim,upstart:-user'
      - '-namemapping=upstart,(-user)'
    restart: unless-stopped
    expose:
      - 9256
    ports:
      - 9256:9256    
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```
